### PR TITLE
mocked auth documentation first draft

### PR DESCRIPTION
**Pull request by bramleyjl**

### CODE REVIEW

**Comment by asg5704** [comment]
@bramleyjl I added some things to the documentation first draft, looks good

**Comment by bramleyjl** [comment]
> @bramleyjl I added some things to the documentation first draft, looks good

Do you still have this locally? I think I accidentally wiped out your contributions when I changed some different files on the branch & pushed it up.

**Comment by asg5704** [comment]
@bramleyjl I merged my Pull Request into your branch. 👍

**Comment by bramleyjl** [comment]
API mocked authentication guide completed.

**Review by asg5704 — APPROVED** [review]
👍  Looks good. I might edit the Client-side afterwards once I get the Rails rendering working.

**Pull request merged**
