### PR TITLE
Update redirects.md

### PR DESCRIPTION
**Pull request by megzehn**
I'm adding a few draft changes to help the content team refine our process for archiving pages in Drupal.

### CODE REVIEW

**Comment by megzehn** [comment]
Hi @saratorres2 and @aprocik1, after talking with @RLHecht and Ian from the CMS team, I drafted some changes to this IA process doc to clarify the archive process. Could you both review when you have a minute? Thank you!

**Comment by aprocik1** [comment]
@megzehn, I think this process looks good. Thanks for updating it.

One question: What does this bullet point mean?

> Content team writer clones a page and updates the URL in Drupal 1. Changing URL for R&S 2. Cloning a page process, specific to updating benefit rates

It's in the "responsibility of content team" section.

**Comment by megzehn** [comment]
Great question, @aprocik1! I *think* those were intended to be links to other processes where we clone a page. I went ahead and made it clearer in our documentation [how to clone a page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/how-to-change-url-in-resources-and-support.md#how-to-clone-a-page). And then I replaced the numbered content with that link.

**Comment by megzehn** [comment]
I cleared this with @bethpotts, and I'm going to go ahead and merge.

**Pull request merged**
