### PR TITLE
Update form-confirmation-page.md

### PR DESCRIPTION
**Pull request by taylojill**
Hello @GnatalieH and @humancompanion-usds I added the Helpful content section, including a screen shot. Please review and provide feedback. Also, I'd like to learn how to convert it to a component. Thanks!

### CODE REVIEW

**Comment by taylojill** [comment]
Hello @GnatalieH I'm following up on the review request. Please let me know if it went through. Thanks!

**Comment by GnatalieH** [comment]
@taylojill thanks for tagging me. The screenshot looks a little blurry, so I am wondering if setting a max width would help fix that. I sometimes have that issue when uploading screenshots, as well. Are you suggesting we make a Web component for Need help? Thx. CC @humancompanion-usds

**Comment by taylojill** [comment]
Thanks @GnatalieH I'll try max width on the screen shot. Matt mentioned that he would like to convert the Helpful content to a component. I'm not sure of the process but I'm willing to give it a try. cc @humancompanion-usds

**Comment by humancompanion-usds** [comment]
This page has where we landed: https://design.va.gov/templates/forms/confirmation

**Pull request closed without merging**
