### PR TITLE
Add zenhub page with zenhub license request info

### PR DESCRIPTION
**Pull request by karlbrown-va**
Per slack discussion with Kevin, I wanted to create this page to capture zenhub information, and document a process for getting a license and requesting help.

If there is another page that has this info please let me know and I can update that page instead.

If not, this page can serve as a clearing house for additional zenhub information, and we can point other pages on the site to it as needed.

### CODE REVIEW

**Review by zachgoldfine44 — COMMENTED** [review]
This looks good. Thanks for taking the time to make this. 

Also, the Epic Templates link has an extra `h` before `https`.

**Review by andreahewitt-odd — COMMENTED** [review]
I think this looks good but a little concerned about putting high_level_orientation_links.md there. @meganhkelley -- do you have thoughts?

**Comment by karlbrown-va** [comment]
Hi @zachgoldfine44  thanks for the review and sharp eyes - I've fixed that link. Not sure why my link checker didn't detect that 😢 

@andreahewitt-odd re: the `high_level_orientation_links.md` file - this file actually existed before, it was one of the few that mentioned Zenhub and linked to Zenhub information; Then @gunsch deleted it (causing a conflict) about a week ago. 

I've thus added it back for now, but if there's a better place for the jump-off to zenhub.md to live I'm all ears. I actually found that high-level pointer file useful, because there is so much content it is useful to have the high-level links available.

**Comment by gunsch** [comment]
Can we drop high_level_orientation_links.md? Nothing else links _to_ it in our codebase, and it's just a random collection of links with little to no context, and wasn't authored or maintained by our team.

I'm open to any number of other areas to link to the ZenHub docs, but that doc is not helpful supplementary material as-is.

**Comment by karlbrown-va** [comment]
@andreahewitt-odd @gunsch I've added the zenhub links to a few other places and removed the high_level_orientation page. Is this good enough to go for now, we can continue to iterate on other links later as well.

**Review by gunsch — COMMENTED** [review]
cool, thanks for tweaking that --- no objections from my end, but @andreahewitt-odd should probably approve overall

**Comment by karlbrown-va** [comment]
Confirmed with @andreahewitt-odd that this is ok to merge. Closing this.

**Pull request merged**
