### PR TITLE
severity-rubric

### PR DESCRIPTION
**Pull request by 1Copenut**
Creating a new severity rubric that will match up to new labels and uses a 508 shorthand-in-progress

### CODE REVIEW

**Comment by 1Copenut** [comment]
@mnorthuis && @peggygannon I'd appreciate your review if you've got a few minutes. I'm adding labels to the `va.gov-team` repo for 508 issue triage and migrating/updating this document to match. Thank you!

**Comment by mnorthuis** [comment]
2 questions:
1) do these labels match up with how other teams are labeling severity?  Would be nice if everyone used the same labels and approach.
2) Are people putting too many things into "critical" so we need a "show-stopper" class?  Typically a "critical" is a show-stopper in my experience.

**Comment by 1Copenut** [comment]
> 2 questions:
> 
> 1. do these labels match up with how other teams are labeling severity?  Would be nice if everyone used the same labels and approach.
> 2. Are people putting too many things into "critical" so we need a "show-stopper" class?  Typically a "critical" is a show-stopper in my experience.

Thank you for the feedback @mnorthuis . Answers below.
1. As far as I know, the only other team using severity labeling is Triage. They have three levels of severity, and [specific criteria](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Triage/Rules%20of%20Engagement%20with%20Triage.md) around notification. I created the 508-specific labeling so teams can readily identify these issues, and triage them with some more granularity.
2. The labels match up with how our automated scan tools (Axe and Attest) define issues, with the Level 0 Showstopper added by my own judgement call. I don't feel the labels are being overused and would like to maintain this level of granularity.

**Review by peggygannon — APPROVED** [review]
@1Copenut Hi, Trevor, I reviewed the severity rubric and made some edits. This is a really informative doc! Looks good.

**Comment by 1Copenut** [comment]
Thank you @peggygannon for the edits. I'll go ahead and merge the doc.

**Pull request merged**
