### PR TITLE
Removing PIV warnings, making COR question first

### PR DESCRIPTION
**Pull request by b00klegger**
Update to issue template to remove PIV warnings and elevate the request for the COR contact name to better fit the launch workflow.

### CODE REVIEW

**Review by ricetj — COMMENTED** [review]
Maybe it should say: Please provide your Contracting Officer's Representative (COR) name.

**Comment by b00klegger** [comment]
> 
> 
> Maybe it should say: Please provide your Contracting Officer's Representative (COR) name.
@ricetj 
Where in the template? It is in the description currently.

**Comment by ricetj** [comment]
> > Maybe it should say: Please provide your Contracting Officer's Representative (COR) name.
> > @ricetj
> > Where in the template? It is in the description currently.

Yes, that would be the first question. I just added the word "your"

**Comment by b00klegger** [comment]
@ricetj 
Alright check it out now. I think we're good to go on the issue template

**Review by ricetj — APPROVED** [review]
Awesome Thanks!.

**Pull request merged**
