### PR TITLE
Create missing-text-equivalent.md

### PR DESCRIPTION
**Pull request by 1Copenut**
Adding the third document for fixing alternative text problems in Microsoft Word documents, and verifying them in Adobe Acrobat.

### CODE REVIEW

**Comment by 1Copenut** [comment]
@gmaciolek Bumping this one when you have a few minutes to review. Thank you!

**Comment by shiragoodman** [comment]
@peggygannon can you please look at this?

**Review by peggygannon — APPROVED** [review]
hi, @1Copenut this document looks good to me. No changes on my end

**Comment by 1Copenut** [comment]
Thank you @peggygannon ! I'll ship it as a good way to end the week.

**Pull request merged**
