### PR TITLE
Facility locator docs reorg

### PR DESCRIPTION
**Pull request by jilladams**
The Facility Locator product documentation needs to be refreshed from a technical perspective. In order to do this, I am proposing a re-org of the directory, to make it easier for modern maintainers to discern: 
* What is modern / relevant for product maintenance
* What is historical
* Where should documentation live, for technical aspects of the product

**For any page I have moved:** I have checked the full Team documentation repo for references to it, and updated the link, so hopefully no broken links (though bookmarks will be affected).

**Changes I've made here:** 
Commits list spells everything out in more detail: https://github.com/department-of-veterans-affairs/va.gov-team/pull/67856/commits
* Created a facility-locator/initiatives folder, and moved previous & current initiatives into it
* Moved the /data/ directory into /engineering
* Within /engineering
  * Created an OLD_DOCS directory and moved old word docs, etc etc into it. I don't think they'll be useful again, but they're still findable just in case.
  * Moved error_states.md into /eng
  * Moved technical-documentation.md into /eng
  * Consolidated information from 2 other .md files (backend documentation / API data) into the /engineering README doc, and deprecated those files

**STILL TO DO:**
* The API documentation and Data sources is still too many docs, with too much old / conflicting information, and no one modern source of truth for how the product works today. We need to fix that and archive anything that isn't true today. 
* Figure out what the deal is with mapbox / the older predictive geolocation spike / locative-rules.md -- make a single place where we say sensible things about how our Mapbox implementation works
* IMO: Consolidate reporting-inaccurate-data.md into Incident response, so we have one place we look for info on problems / how to correct them. 
* Review everything in /engineering/data and determine what's accurate, rearrange it to make sense (e.g. we have a /data/data-sources/ dir, but /ppms and /community-care were not in it, etc), and consolidate .md files as needed.
  

* Updated all the links I found to point to new file locations

### CODE REVIEW

**Comment by jilladams** [comment]
@mmiddaugh obviously I defer to you for any requirements here, and happy to discuss if you have concerns about these changes.

**Comment by jilladams** [comment]
How the filetree / org structure will look post-merge: 
Screenshot 2023-10-17 at 3 34 58 PM

**Comment by jilladams** [comment]
@eselkin @maxx1128 @xiongjaneg @davidmpickett FYSA

**Comment by maxx1128** [comment]
I'm looking at the changes so far; it all looks like a positive step forward. I especially like moving the technical documentation to the engineering folder (my default assumption of where they'd be) and keeping the old documents in a separate folder in case they're needed later.

My only suggestion this early on is to rename `OLD_DOCS` to `archive` since it's more clear that they're documents no longer being used but are still being saved. Other than that, 👍

**Pull request merged**
