### PR TITLE
Update 508-issue.md

### PR DESCRIPTION
**Pull request by cvalarida**
I moved the user story to its own section to avoid confusion, renamed `Possible Fixes (optional)` and `Description`, and moved the `Point of Contact` section up so the user story, details, and acceptance criteria are all back-to-back.

### CODE REVIEW

**Review by jenstrickland — APPROVED** [review]
LGTM! Thank you!

**Review by 1Copenut — CHANGES_REQUESTED** [review]
These are big improvements, thank you @cvalarida . I have one change request, and that's to ask that we move the Definition of Done underneath the acceptance criteria. I've missed that section a number of times when writing (and reviewing) issue tickets because I'm accustomed to seeing screenshots last.

/cc @jenstrickland

**Comment by cvalarida** [comment]
Done!

**Review by 1Copenut — APPROVED** [review]
👍 LGTM!

**Pull request merged**
