### PR TITLE
Itharrison patch

### PR DESCRIPTION
**Pull request by it-harrison**
This PR adds a checkbox to the Platform Orientation template for va.gov team members who are veterans.

### CODE REVIEW

**Comment by andaleliz** [comment]
Thanks for including me in this! I think it looks good, though perhaps a bit more context in the link (e.g. "Veterans willing to help VA teams with product testing") would help? Not sure who provided content for this.

**Comment by it-harrison** [comment]
> Thanks for including me in this! I think it looks good, though perhaps a bit more context in the link (e.g. "Veterans willing to help VA teams with product testing") would help? Not sure who provided content for this.

@andaleliz good call - I updated the text.

**Review by bethdeconinck — CHANGES_REQUESTED** [review]
Hey @it-harrison! I'm confused about one thing: I'm seeing a checkbox for the Collaboration Point Tracker on the line just above the "Are you a Veteran?" line. That's not in the [current master branch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md) and I think it was removed in May or so. Not sure if it just snuck back in or if that's something you were including intentionally.

**Comment by it-harrison** [comment]
> Hey @it-harrison! I'm confused about one thing: I'm seeing a checkbox for the Collaboration Point Tracker on the line just above the "Are you a Veteran?" line. That's not in the [current master branch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/orientation-epic.md) and I think it was removed in May or so. Not sure if it just snuck back in or if that's something you were including intentionally.

@briandeconinck - good catch, I must not have pulled before branching. Fixed now.

**Review by bethdeconinck — APPROVED** [review]

**Pull request merged**
