### PR TITLE
Med review language proposal

### PR DESCRIPTION
**Pull request by outerpress**
Please review the language proposed in [this file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/05-24-med-review-lang-proposal/products/health-care/appointments/projects/2024-05-medication-language-update/proposed-language.md) on this branch. You can edit the content directly, or add comments to this PR and I'll make the updates.

### CODE REVIEW

**Comment by outerpress** [comment]
I'm thinking this content could be accessed as needed in an additional info component. It's not something everyone will have to read every time. Something like:

```
{h2} Prepare for your visit

Bring a list of your medications to review with your provider. 
{Addl Info Link} More information

> Final med review content

{End Addl Info Content}
```

Thoughts @laurwill @kristenmcconnell ?

@mistymg does mobile have similar UI that could support this?

**Comment by mistymg** [comment]
@outerpress Yes, we have a link component that when tapped opens a large panel (a modal). My only concern though is that  "More information" is not really helpful content for link copy. Wondering if @laurwill or @DanielleThierryUSDSVA agree that "more information" needs to changed. Maybe something more like "Learn what medication information to share with your provider" or "Find out what medication information to share with your provider"? This is where seeing it in a design mock up would eventually help to see how the copy and UI are playing with one another.

**Comment by outerpress** [comment]
@mistymg I did a mock of the proposed language in our [content library](https://www.figma.com/design/enGXBfuvpWJOQp0onrWgHs/%5BDRAFT%5D-Content-Library-%7C-MHV---Unified-Appointments?node-id=171-2165&t=fLd2k0iWqisNJzTe-4) if it helps to see the placement with the rest of the content. (With the caveat that this is all WIP so all comments are welcome :) )

**Comment by mistymg** [comment]
@outerpress @laurwill @DanielleThierryUSDSVA If we use the link component that opens to a modal, this is what it would look like in mobile app. Some concerns:

**Comment by outerpress** [comment]
@mistymg I updated the proposal based on [this Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1715629254839119):
- Tweaked the additional info trigger language
- Added an example showing the language in web

I'll drop your examples in the linked Figma file, and get Check-in in there next.

**Comment by outerpress** [comment]
No further changes to the Medication Review language so merging this into main. Next step is review with NAPMIS and other stakeholders. 

- Content source of truth is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/projects/2024-05-medication-language-update/proposed-language.md)
- Examples in context are [here](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-2)

**Pull request merged**
