### PR TITLE
Public Websites: header footer & income limits file updates

### PR DESCRIPTION
**Pull request by jilladams**
* Federal header footer files moved to initiatives folder
  * Old path: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/federal-standardized-header-footer
  * New path: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/header-footer/initiatives/2024-federal-standardized-header-footer
* Income Limits: created initiatives structure and moved existing research into launch-related folder
  * Old path: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/research
  * New path: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/initiatives/2023-launch/research

### CODE REVIEW

**Comment by jilladams** [comment]
FYI @cindymerrill that I'd like to make this structural change, when you have a break in editing your phase 2 research plan. I'll need to update my branch when you have a gap (not today, as I'm headed out in a minute, so later this week is fine with me, just lemme know when there's an hour I could do it).

**Comment by jilladams** [comment]
Also FYI @FranECross once this PR merges, I'm creating a decision log for the header / footer project, you can preview it here (won't be editable til this PR merges): https://github.com/department-of-veterans-affairs/va.gov-team/blob/b2c4f712a0eb8d21733464541bba8806f5ca1f33/products/header-footer/initiatives/2024-federal-standardized-header-footer/decision-log.md

**Comment by cindymerrill** [comment]
@jilladams So you want to change the path of my files when I'm not editing them, and then I should update the research repo? I prefer to do this before my research sessions next week, so how about sometime Thu or Fri? I can look for an hour when we're both free...

**Comment by cindymerrill** [comment]
@jilladams I scheduled an hour for us on Thursday afternoon, but if we don't have to do it together, I'll be at a doctor's appointment on Friday morning from ~9-11 am PT if you want time to make the change without me touching any of the files.

**Comment by cindymerrill** [comment]
@jilladams Will you update all the URLs within files (like in my research plans and convo guides) so I'll only need to make URL changes in the research repo?

**Comment by cindymerrill** [comment]
The URLs inside my research files for income limits (including [discovery research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/initiatives/2023-launch/research/research-plan.md) and [usability testing research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/initiatives/2023-launch/research/2023-01-income-limits-usability/research-plan.md)) have NOT been updated and now are all broken. Also the research reports from each study have URLs that are also affected. @jilladams Please let me know if you can fix them all at once. Thanks!

**Comment by cindymerrill** [comment]
@jilladams updated all the URLs inside 4 research folders for header/footer and income limits, and I updated the 4 URLs in the VA Research Repo.

**Pull request merged**
