### PR TITLE
Add RFC 4 for PST-CIT team

### PR DESCRIPTION
**Pull request by dginther**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/dg/pst-cit/RFC-4/teams/vsp/teams/pst-cloud-isolation-team/RFC/4-Removing-Kong-as-an-intermediary-between-vets-api-and-LH-in-cases-of-upstream-dependencies.md

### CODE REVIEW

**Comment by dginther** [comment]
From Patrick Vinograd:
I think there's a chicken and egg problem here. In the diagram above, step (4) shows the link from forward proxy to Lighthouse as being via 4. api.va.gov/services/va_facilities/ But that URL is still routing to Kong, until such time as Apigee is deployed and VA DNS is updated to route traffic for api.va.gov to Apigee. But perhaps we're not ready to do that cutover until Kong is decommissioned for these internal uses?

At minimum I think the more accurate thing would be to say that step (4) routes to Lighthouse at the configured upstream for the forward proxy, which is blue.qa.lighthouse.va.gov:443. In other words going straight from vets-api (via fwdproxy) to the upstream API application server, much like we do with other upstream dependencies for VA.gov. But, this carries with it some measure of risk because now there's no rate limiting or access control in front of that Lighthouse endpoint (because those capabilities were provided by Kong).

My question is - my understanding is that Apigee is intended as the public API gateway for external-to-VA Lighthouse clients. But vets-api is not really one of these - it's an internal-to-VA client. So what is the URL/route that internal Lighthouse clients are meant to use? Is such thing deployed yet, and can we point from vets-api->fwdproxy-> ? Otherwise, we need to be clear on the risk of bypassing Kong.

**Comment by dginther** [comment]
From Patrick Vinograd:
I think there's a chicken and egg problem here. In the diagram above, step (4) shows the link from forward proxy to Lighthouse as being via 4. api.va.gov/services/va_facilities/ But that URL is still routing to Kong, until such time as Apigee is deployed and VA DNS is updated to route traffic for api.va.gov to Apigee. But perhaps we're not ready to do that cutover until Kong is decommissioned for these internal uses?

At minimum I think the more accurate thing would be to say that step (4) routes to Lighthouse at the configured upstream for the forward proxy, which is blue.qa.lighthouse.va.gov:443. In other words going straight from vets-api (via fwdproxy) to the upstream API application server, much like we do with other upstream dependencies for VA.gov. But, this carries with it some measure of risk because now there's no rate limiting or access control in front of that Lighthouse endpoint (because those capabilities were provided by Kong).

My question is - my understanding is that Apigee is intended as the public API gateway for external-to-VA Lighthouse clients. But vets-api is not really one of these - it's an internal-to-VA client. So what is the URL/route that internal Lighthouse clients are meant to use? Is such thing deployed yet, and can we point from vets-api->fwdproxy-> ? Otherwise, we need to be clear on the risk of bypassing Kong.

**Comment by dginther** [comment]
From Andrea Singh: 
@patrickvinograd I've changed step 4 in the diagram to correctly use the url configured in the fwd proxy, which is blue.qa.lighthouse.va.gov:443. Also, really good question about coordinating the switch to Apigee and which endpoint to configure in the forward proxy for the transition!

**Comment by dginther** [comment]
From Andrea Singh: 
@patrickvinograd I've changed step 4 in the diagram to correctly use the url configured in the fwd proxy, which is blue.qa.lighthouse.va.gov:443. Also, really good question about coordinating the switch to Apigee and which endpoint to configure in the forward proxy for the transition!

**Comment by dginther** [comment]
From Beau Grantham:
In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.

Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.

**Comment by dginther** [comment]
From Beau Grantham:
In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.

Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.

**Comment by dginther** [comment]
> From Beau Grantham: In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.
> 
> Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.



> From Beau Grantham: In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.
> 
> Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.

From Andrea Singh:
Right, I will add a note that this is a temporary URL to bypass Kong and directly access the API application server. Or do you have any suggestions what domain to use instead to make the scenario clear, e.g. tbd-apigee-dns.va.gov or something like that?

**Comment by dginther** [comment]
> From Beau Grantham: In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.
> 
> Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.



> From Beau Grantham: In the new architecture diagram, routing directly to blue.[env].lighthouse.va.gov bypasses the Lighthouse gateway and its policies. All clients (including VA.gov / vets-api) should go through the Lighthouse gateway.
> 
> Unless, as Patrick points out, Lighthouse approves unrestricted backchannel traffic for very specific scenarios/sources.

From Andrea Singh:
Right, I will add a note that this is a temporary URL to bypass Kong and directly access the API application server. Or do you have any suggestions what domain to use instead to make the scenario clear, e.g. tbd-apigee-dns.va.gov or something like that?

**Comment by patrickvinograd** [comment]
Those most recent comments by Beau and Andrea are the crux of the matter for me.
* End state should be that VA.gov, like any other LH client, access APIs through the LH API gateway
* But if the intended LH API gateway is Apigee hosted at api.va.gov, then we have an order of operations problem.

So either:
1) There's a different **temporary** Apigee endpoint that VA.gov can use. 
2) There's a different **permanent** Apigee endpoint that VA.gov can use, since it's an internal client. 
3) There's a temporary non-Apigee endpoint that VA.gov can use (like set up a short-lived Kong instance in front of the DVP endpoints)
4) We accept the risk of **temporary** direct API access without an API gateway.

**Pull request merged**
