### PR TITLE
Add RFC 3 for PST CIT team

### PR DESCRIPTION
**Pull request by dginther**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/dg/pst-cit/RFC-3/teams/vsp/teams/pst-cloud-isolation-team/RFC/3-Platform-will-give-api.va.gov-URL-to-Lighthouse.md

### CODE REVIEW

**Comment by dginther** [comment]
from Kyle Soskin:
My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:

Need to be changed every where to reference new api url
Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs.
I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?

If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.

**Comment by dginther** [comment]
from Kyle Soskin:
My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:

Need to be changed every where to reference new api url
Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs.
I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?

If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.

**Comment by dginther** [comment]
> from Kyle Soskin: My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:
> 
> Need to be changed every where to reference new api url Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs. I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?
> 
> If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.



> from Kyle Soskin: My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:
> 
> Need to be changed every where to reference new api url Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs. I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?
> 
> If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.

From dginther:
As far as I know, this is not a scenario that we have, but I am hoping that folks from both the vets-api side of things and the lighthouse side of things come to comment on this, so that we can find any possible things like that.

I am not sure that there are many users of the vets-api services that are outside our ecosystem, and casual investigation seems to bear that out, but more in-depth is needed.

The biggest issue with keeping the single URL is that Lighthouse is moving their APIs to Google Apigee, and a completely separate cloud service, so if we continue to route things inside our network, we will end up traversing the TIC possibly 3-4 times on a single request, which will introduce unacceptable latency.

**Comment by dginther** [comment]
> from Kyle Soskin: My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:
> 
> Need to be changed every where to reference new api url Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs. I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?
> 
> If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.



> from Kyle Soskin: My only comment about NOT "continue[ing] having Lighthouse and vets-api share the same URL (api.va.gov)" is that many apis or services already connected to or using the api will both:
> 
> Need to be changed every where to reference new api url Will also need to have logic that lives on their side in their app to decide which api to hit if it is using components that will reside in both separated APIs. I wonder which is more painful, managing the routing to the 2 apis behind the existing single url everyone already uses, or having every/any app that already uses the api change its' url and implement logic to decide which api to hit?
> 
> If there aren't any apps that use components from both api locations I guess that doesn't matter, but I don't know enough about it to know, so just raising the question.

From dginther:
As far as I know, this is not a scenario that we have, but I am hoping that folks from both the vets-api side of things and the lighthouse side of things come to comment on this, so that we can find any possible things like that.

I am not sure that there are many users of the vets-api services that are outside our ecosystem, and casual investigation seems to bear that out, but more in-depth is needed.

The biggest issue with keeping the single URL is that Lighthouse is moving their APIs to Google Apigee, and a completely separate cloud service, so if we continue to route things inside our network, we will end up traversing the TIC possibly 3-4 times on a single request, which will introduce unacceptable latency.

**Comment by dginther** [comment]
From Rebecca Tolmach:
If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.

We believe there are consumers who would need this functionality.

I agree that more research is needed on how many services this change will impact.

Feedback on suggested subdomains:
I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.

**Comment by dginther** [comment]
From Rebecca Tolmach:
If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.

We believe there are consumers who would need this functionality.

I agree that more research is needed on how many services this change will impact.

Feedback on suggested subdomains:
I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.

**Comment by dginther** [comment]
> From Rebecca Tolmach: If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.
> 
> We believe there are consumers who would need this functionality.
> 
> I agree that more research is needed on how many services this change will impact.
> 
> Feedback on suggested subdomains: I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.



> From Rebecca Tolmach: If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.
> 
> We believe there are consumers who would need this functionality.
> 
> I agree that more research is needed on how many services this change will impact.
> 
> Feedback on suggested subdomains: I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.

My biggest concern with using vets-api.va.gov would be if we were to integrate some other microservice which was not part of vets-api, would that still be an appropriate URL? Generic is what I was aiming for, to be honest.

**Comment by dginther** [comment]
> From Rebecca Tolmach: If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.
> 
> We believe there are consumers who would need this functionality.
> 
> I agree that more research is needed on how many services this change will impact.
> 
> Feedback on suggested subdomains: I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.



> From Rebecca Tolmach: If keeping one single URL adds significant latency, I agree that having two separate subdomains would be the better way to go.
> 
> We believe there are consumers who would need this functionality.
> 
> I agree that more research is needed on how many services this change will impact.
> 
> Feedback on suggested subdomains: I don't love the "platform" prefix for the external api. It feels too generic to me. "vets-api.va.gov" is my preference, but I can brainstorm alternatives.

My biggest concern with using vets-api.va.gov would be if we were to integrate some other microservice which was not part of vets-api, would that still be an appropriate URL? Generic is what I was aiming for, to be honest.

**Comment by dginther** [comment]
From Dina Steeve:
I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?

Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?

**Comment by dginther** [comment]
From Dina Steeve:
I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?

Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?

**Comment by dginther** [comment]
> From Dina Steeve: I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?
> 
> Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?



> From Dina Steeve: I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?
> 
> Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?

There's no 'like' or 'dislike' involved in this situation, the Lighthouse team is of course free to do whatever they want to do.

In the architecture diagram which Lighthouse has presented, there are some requests which might traverse the TIC more than once, and that could introduce significant latency into the system, for sure.

There is an explainer document here: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap

and a Direction setting document here: https://docs.google.com/document/d/1i0WgBFcOK0sL1x_WL5V7JMDRxPsM9aRcszput9iVkp8/edit#heading=h.o1b49rfssykx

which might explain a little bit more about why we are doing this

**Comment by dginther** [comment]
> From Dina Steeve: I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?
> 
> Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?



> From Dina Steeve: I am left confused, because I thought the purpose of the Lighthouse Program was to onboard all the API's that the VA has (I know all is a stretch) - and have them be in one catalog all flow thru a single managed gateway/platform. It was my understanding that the VA wanted to stop having every group go off and do their own thing. Sounds like that is what this proposal is?
> 
> Is this because of the Apigee concern of the gateway being in Google Cloud and the latency that would seemingly create being in the AWS cloud for the actual services? In other words, you don't like the architecture that the Lighthouse Program is doing and wish to separate yourself?

There's no 'like' or 'dislike' involved in this situation, the Lighthouse team is of course free to do whatever they want to do.

In the architecture diagram which Lighthouse has presented, there are some requests which might traverse the TIC more than once, and that could introduce significant latency into the system, for sure.

There is an explainer document here: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1907523684/Explainer+-+VA.gov-Lighthouse+Overlap

and a Direction setting document here: https://docs.google.com/document/d/1i0WgBFcOK0sL1x_WL5V7JMDRxPsM9aRcszput9iVkp8/edit#heading=h.o1b49rfssykx

which might explain a little bit more about why we are doing this

**Comment by dginther** [comment]
From Tim Wright:
Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.

Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.

I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well

**Comment by dginther** [comment]
From Tim Wright:
Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.

Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.

I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well

**Comment by dginther** [comment]
> From Tim Wright: Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.
> 
> Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.
> 
> I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well



> From Tim Wright: Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.
> 
> Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.
> 
> I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well

There is no intention to give the *api.va.gov URLs to Lighthouse until we have a solution which is externally accessible (in the case that an external URL is needed, which appears to be necessary) already in place.

There is no intention to have anyone use SOCKS to access this API, ever.

vets-website apps would never be expected to access vets-api from *.vfs.va.gov

What are you concerned about with reference to review instances and GHA workflows and Jenkins, in particular?

I'll modify the RFC to make this clear, but it's good to know that we will definitely need an external URL.

**Comment by dginther** [comment]
> From Tim Wright: Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.
> 
> Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.
> 
> I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well



> From Tim Wright: Agreeing with @kylesoskin and @rmtolmach that some more research may be needed to gauge impact. I might be missing something in the architecture, but there are a ton of apps that use vets-api, especially for feature toggles that need it to be publicly accessible to work, so pulling it behind SOCKS, even temporarily would break the site.
> 
> Again, there might be something I'm missing or maybe we can add to this doc to clarify what happens to the vets-website apps accessing vets-api from *.vfs.va.gov and how long that period would be.
> 
> I'm sure there's work to update review instances and GHA workflows/jenkins(?) as well

There is no intention to give the *api.va.gov URLs to Lighthouse until we have a solution which is externally accessible (in the case that an external URL is needed, which appears to be necessary) already in place.

There is no intention to have anyone use SOCKS to access this API, ever.

vets-website apps would never be expected to access vets-api from *.vfs.va.gov

What are you concerned about with reference to review instances and GHA workflows and Jenkins, in particular?

I'll modify the RFC to make this clear, but it's good to know that we will definitely need an external URL.

**Comment by dginther** [comment]
> there are a ton of apps that use vets-api

Can you clarify this comment, @timwright12 ? Do you mean that there are applications other than VA Mobile and vets-website that access the vets-api APIs via the external internet?

**Comment by dginther** [comment]
> there are a ton of apps that use vets-api

Can you clarify this comment, @timwright12 ? Do you mean that there are applications other than VA Mobile and vets-website that access the vets-api APIs via the external internet?

**Comment by dginther** [comment]
> > there are a ton of apps that use vets-api
> 
> Can you clarify this comment, @timwright12 ? Do you mean that there are applications other than VA Mobile and vets-website that access the vets-api APIs via the external internet?

From Tim Wright:
Just those two, but I'm considering vets-website a collection of applications rather than just 1. I should've clarified there, we have 71 React apps inside vets-website that use vets-api to varying degrees at different time.

**Comment by dginther** [comment]
> > there are a ton of apps that use vets-api
> 
> Can you clarify this comment, @timwright12 ? Do you mean that there are applications other than VA Mobile and vets-website that access the vets-api APIs via the external internet?

From Tim Wright:
Just those two, but I'm considering vets-website a collection of applications rather than just 1. I should've clarified there, we have 71 React apps inside vets-website that use vets-api to varying degrees at different time.

**Comment by dginther** [comment]
From Andrea Singh:
[This document](https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov) lists the expected changes that the new domain separation is likely to bring, such as:

Routes that will in future only be accessible from the new domain platform-api.va.gov
Routes that will in future be accessible both from the existing domain and the old domain (api.va.gov and platform-api.va.gov)
Routes that will in future only be accessible from the existing domain api.va.gov
We're seeing input and feedback from people who work with these API to make sure we're on the right track and didn't miss anything.[This document](https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov) lists the expected changes that the new domain separation is likely to bring, such as:

Routes that will in future only be accessible from the new domain platform-api.va.gov
Routes that will in future be accessible both from the existing domain and the old domain (api.va.gov and platform-api.va.gov)
Routes that will in future only be accessible from the existing domain api.va.gov
We're seeing input and feedback from people who work with these API to make sure we're on the right track and didn't miss anything.

**Comment by dginther** [comment]
From Andrea Singh:
[This document](https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov) lists the expected changes that the new domain separation is likely to bring, such as:

Routes that will in future only be accessible from the new domain platform-api.va.gov
Routes that will in future be accessible both from the existing domain and the old domain (api.va.gov and platform-api.va.gov)
Routes that will in future only be accessible from the existing domain api.va.gov
We're seeing input and feedback from people who work with these API to make sure we're on the right track and didn't miss anything.[This document](https://vfs.atlassian.net/wiki/spaces/PST4/pages/2143977624/Set+of+routes+to+be+served+by+platform-api.va.gov) lists the expected changes that the new domain separation is likely to bring, such as:

Routes that will in future only be accessible from the new domain platform-api.va.gov
Routes that will in future be accessible both from the existing domain and the old domain (api.va.gov and platform-api.va.gov)
Routes that will in future only be accessible from the existing domain api.va.gov
We're seeing input and feedback from people who work with these API to make sure we're on the right track and didn't miss anything.

**Comment by madebydna** [comment]
Closing this RFC as resolved. The ADR related to new domain name: https://vfs.atlassian.net/wiki/spaces/ECP/pages/2221572288/2022-06-06+New+domain+to+serve+vets-api

**Pull request merged**
