### PR TITLE
Create inventory-of-content-style-guides

### PR DESCRIPTION
**Pull request by jenniferlee-dsva**
[Content-guides-VA-USDS-list-101018.xlsx] https://github.com/department-of-veterans-affairs/va.gov-team/files/2466334/Content-guides-VA-USDS-list-101018.xlsx 

In-progress spreadsheet of USDS and VA-related content style guides. Please add to this doc any that’s missing. There are lots of areas where I just have ? marks inserted (someone’s role or name spelling, etc.). If you know the answer, please feel free to add them and upload an updated spreadsheet. Also, if you have examples of style guides that you really like, include those in the worksheet "Examples we like."

### CODE REVIEW

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. I've added some docs, including the 2 that I mentioned to you yesterday on our call that Jenny H-L and Jeff Grandon from VHA had requested to help train folks at their VA medical centers (our plain language checklist + a quick tips specific to health care that I just created for them today). Also added SEO and error message guides. Highlighted new rows in yellow.

I'll ask Jenny and Jeff if they have a VHA style guide they can share as well. Thanks!
[Content-guides-VA-USDS-list-101118.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/2470413/Content-guides-VA-USDS-list-101118.xlsx)

**Comment by DanielleSoCompany** [comment]
@jenniferlee-dsva A couple of other research/recommendations efforts that may be helpful:

- **[How to Talk about Help](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/10414):** Research and recommendations that have helped to inform changing "Get help" to "Contact us" and related copy.

- **[Asking for Gender on Forms]:(https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/7462)** Research and recommendations around asking for gender on forms. I know that VA had updated the health care application form gender question separately, and they may have additional guidance around this.

**Comment by DanielleSoCompany** [comment]
@jenniferlee-dsva Got the VHA style guide. Updated spreadsheet below.

[Content-guides-VA-USDS-list-101118-2.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/2470611/Content-guides-VA-USDS-list-101118-2.xlsx)

**Comment by jenniferlee-dsva** [comment]
I'm closing this PR branch. Danielle's file has been added via 22b1e7f. Please go to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/design/content/inventory-content-style-guides/ to add more to the latest spreadsheet.

**Pull request closed without merging**
