### PR TITLE
VACMS-19259: DUW v2 QA testing artifact

### PR DESCRIPTION
**Pull request by chriskim2311**
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19259

### CODE REVIEW

**Comment by jilladams** [comment]
@chriskim2311 I saw Fran had started a template in the existing DUW product folder, over here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/testing-qa.md.  Could you update this PR to overwrite that file, rather than create a new one? 

(The only file in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Discharge%20Upgrade%20Wizard, is a redirect to point to that `veteran-military-records` path instead.

**Comment by chriskim2311** [comment]
@jilladams @FranECross  Updated the correct file with my changes. One thing I have found is the test coverage is a little low. I think its due to the v1 code base not being covered since we are sharing the same folder. And cypress tests are not currently active since we are not running them currently since routes are not live on prod.

**Comment by jilladams** [comment]
Curious: the cypress tests are written and just don't run til we're in prod?

**Comment by chriskim2311** [comment]
Exactly. The tests run against routes that on prod. Since we are keeping this on staging those cypress tests will fail.

**Review by jilladams — APPROVED** [review]

**Comment by FranECross** [comment]
@chriskim2311 Since Danielle T isn't going to publish the entry point until we request it post-launch, is it safe to say that until th entry point is there, we'll be able to QA and check the Cypress tests before actual users are active in DUW? I'm thinking of what I can put in the collab cycle ticket so we aren't blocked.

**Comment by chriskim2311** [comment]
@FranECross Yes the tests will not be a part of the CI pipeline until we get the routes live on prod. We have ran them locally and all are passing. These should account for the last 10% of coverage not being accounted for in the test coverage dashboard.

**Comment by FranECross** [comment]
@chriskim2311 Thanks, and some questions/comments for you:

- In section: Overview of app and QA risks, where its asking the testing complexity, is 'moderate' the correct choice to replace the brackets/text in brackets? > The Discharge Upgrade Wizard app has <minimum/moderate/high> complexity from a testing perspective.
- In section: React application complexity: moderate:
  - where it has "Based on the response, the user will be asked between <#> and <#> questions" > would the correct values for the brackets be 'between 5 - 9'?
  - where is says 'There is one answer type: Radio buttons: 1 response per page', wouldn't this be that there are two answer types, radio button and dropdown?
  - The Mural links are broken and going to Github instead of the Mural pages
- In the section Manual Test Cases. I think reference to the answers with drop-downs should be added.
- In the section: Automated Test Coverage, sub sections Unit Test Coverage. In the following sub sections:
  - Shadow DOM Limitations, I see my question in caps/parens (CHRIS, ARE THESE A TRUE STATEMENTS? CAME FROM PAW) is still there. Did you validate that the info is correct? If so, will you please delete that question so I'll know it's been done?
  - Utility: General utilities,  I see my question in caps/parens  (CHRIS, ARE THESE A TRUE STATEMENTS? CAME FROM PAW) is still there. 
    -  The link in this sentence is going to PAW info: All utilities are completely covered by unit tests [here]
  - Unit Test Coverage Statistics (CHIS, YOU'LL WANT TO CORRECT THE DUW NAME IN THE TABLE BELOW, AND ENTER THE STATS)
    - Did you validate that the Application Name is correct?  
    - Also, there aren't any stats in the table. Will you please add? Then if you'll that question so I'll know it's been done that would be great.
(https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/pact-act/tests/utilities).
- In this section Cypress Test Coverage **CHRIS, YOU'LL WANT TO EDIT FOR DUW)
  - Not sure you edited, since my text is still there
  - The link in this sentence is broken: You can refer to [this Mural](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/url) in addition to this written explanation to understand
  - The link in this sentence is broken: There are 25 comprehensive [Cypress test files](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/URL). 
  - It looks like info is missing further down in this section: (A) "During both of these time periods" <- service period response
(B)
The functionality tested within Cypress flows cover the below: 1.

**Comment by FranECross** [comment]
@chriskim2311 Looks great; approved! Thanks.

**Comment by jilladams** [comment]
I'm gonna go ahead and merge this with the note that we'll need a follow up PR to address the unit testing coverage, once that's handled.

**Pull request merged**
