### PR TITLE
Update orientation-epic.md

### PR DESCRIPTION
**Pull request by CherylEvans**
@briandeconinck @vbellissimo @laucon Good morning!  I am working on [Zenhub ticket 54824](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/54824) "Add VFS Orientation to Platform Website" video to Platform Orientation. I created a PR for the first "Task" in the list and would like to invite you all to review the changes I made. 
Please let me know if you have any questions or concerns.  Thank you!!

### CODE REVIEW

**Review by laucon — APPROVED** [review]
This looks great to me.

**Comment by vbellissimo** [comment]
The update looks good to me too @CherylEvans. Thank you for keeping us in the loop!

**Comment by CherylEvans** [comment]
> This looks great to me. I read it carefully. :)

Thank you so much!  :-)

**Comment by CherylEvans** [comment]
> The update looks good to me too @CherylEvans. Thank you for keeping us in the loop!

You are most welcome, Vicky! :-)  Thank you both for getting to this so quickly!

**Review by bethdeconinck — APPROVED** [review]
This looks good to me, sorry for the delay!

**Comment by CherylEvans** [comment]
All parties have approved the changes.

**Pull request merged**
