### PR TITLE
Update orientation-epic.md

### PR DESCRIPTION
**Pull request by shiragoodman**
updated per ticket [#70171](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70171)

### CODE REVIEW

**Comment by rferguson13** [comment]
@shiragoodman - A couple of things:

- I just noticed that we're inconsistent on how we capitalize "Collaboration Cycle." Sometimes we capitalize "cycle," and sometimes we don't. We should be consistent - and probably capitalize both words.
- It might be nice to link the most recent general orientation video (first bullet under "General").

**Review by allison0034 — APPROVED** [review]

**Review by rferguson13 — CHANGES_REQUESTED** [review]
A couple of things:
- I just noticed that we're inconsistent on how we capitalize "Collaboration Cycle." Sometimes we capitalize "cycle," and sometimes we don't. We should be consistent - and probably capitalize both words.
- It might be nice to link the most recent general orientation video (first bullet under "General").

**Review by rferguson13 — APPROVED** [review]

**Comment by shiragoodman** [comment]
@rferguson13 thanks for the suggestions! I'm 100% on board with ensuring we write Collaboration Cycle consistently each time. However, I don't want to link the youtube video from the ticket. The Youtube recording changes every 3 months when we host and rerecord a live session (we do this to prevent the content from getting out of date). We have never had an issue with teams not being able to find the recording from Platform Website, also.

Would you mind rolling back your changes? I was going to do it but I think it would be good practice for you :)

**Review by rferguson13 — APPROVED** [review]

**Comment by rferguson13** [comment]
@shiragoodman Done! Triple check that I didn't mess something up? 😂

**Comment by shiragoodman** [comment]
all good. Thanks @rferguson13 ! merging now.

**Pull request merged**
