### PR TITLE
Migrate product-support-engineering-ds documentation from vets.gov-team

### PR DESCRIPTION
**Pull request by billfienberg**
ZenHub ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3711

Corresponding `vets.gov-team` PR: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20073

image

### CODE REVIEW

**Comment by billfienberg** [comment]
There are three different files competing to be `platform/engineering/frontend`
- https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice Areas/Engineering/Frontend/Readme.md
- https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice Areas/Engineering/Style Guides/README.md
- https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice Areas/Engineering/Style Guides/API/README.md

**Review by thatmattjohnson — COMMENTED** [review]
showing 3 items; migration plan count is 17

**Comment by billfienberg** [comment]
> showing 3 items; migration plan count is 17

image

@thatmattjohnson, I think this batch was particularly confusing because there were four sets of PRs. 
1. From `va.gov-vfs-teams` to `va.gov-team`
1. From `va.gov-vfs-teams` to `va.gov-team-sensitive`
1. From `vets.gov-team` to `va.gov-team`
1. From `vets.gov-team` to `va.gov-team-sensitive`

This PR (4055) is part of the **`vets.gov-team`-to-`va.gov-team`** set. That set should have 5 files changed. However, there are only three files in this PR because there were [three files competing to be `platform/engineering/frontend/README.md`](https://github.com/department-of-veterans-affairs/va.gov-team/pull/4055#issuecomment-563313970). Once we resolve those three conflicting files, this PR should have five files changed, and match the migration plan.

**Comment by thatmattjohnson** [comment]
I was looking at the count in the "va.gov-vfs-teams-to-va.gov-team" you created (n = 17). When I look at the count in the "migration plan" sheet it is correct (n = 5, including 1 file flagged for exclusion to resolve the conflict you call out above). Not sure how to account for the gap between these but if PR is based off of "migration plan" count then we're good.

**Review by thatmattjohnson — APPROVED** [review]
approved

**Pull request merged**
