### PR TITLE
Migrate vfs-teams-product-support-engineering-ds documentation from v…

### PR DESCRIPTION
**Pull request by billfienberg**
…a.gov-vfs-teams

ZenHub ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3711

Corresponding `va.gov-vfs-teams` PR: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/51

image

### CODE REVIEW

**Comment by billfienberg** [comment]
There are two different files competing to be `platform/engineering/frontend/README.md`:
- https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/assets/README.md
- https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/README.md

**Review by thatmattjohnson — COMMENTED** [review]
showing 30 items; migration plan count is 17

**Comment by billfienberg** [comment]
> showing 30 items; migration plan count is 17

image

@thatmattjohnson, I think this batch was particularly confusing because there were four sets of PRs. 
1. From `va.gov-vfs-teams` to `va.gov-team`
1. From `va.gov-vfs-teams` to `va.gov-team-sensitive`
1. From `vets.gov-team` to `va.gov-team`
1. From `vets.gov-team` to `va.gov-team-sensitive`

This PR (4055) is part of the **`va.gov-vfs-teams`-to-`va.gov-team`** set. That set should have 31 files changed. However, there are only 30 files in this PR because there were [two files competing to be `platform/engineering/frontend/README.md`](https://github.com/department-of-veterans-affairs/va.gov-team/pull/4057#issuecomment-563333021). Once we resolve those two conflicting files, this PR should have 31 files changed, and match the migration plan.

**Comment by thatmattjohnson** [comment]
I was looking at the count in the "va.gov-vfs-teams-to-va.gov-team" you created (n = 17). When I look at the count in the "migration plan" sheet it is correct (n = 30). Not sure how to account for the gap between these but if PR is based off of "migration plan" count then we're good.

**Review by thatmattjohnson — APPROVED** [review]
approved

**Pull request merged**
