### PR TITLE
Create tty-and-711-links.md

### PR DESCRIPTION
**Pull request by 1Copenut**
Adding a document on TTY and 711 links from @msmanak

### CODE REVIEW

**Review by peggygannon — CHANGES_REQUESTED** [review]
HI, @1Copenut  I made a few content tweaks in the file. 

I also have a question about this line. I'm not sure if the "yo" should be "your" or if it should be "the".

*Follow the same coding and styling patterns for linking telephone numbers on **yo** platform.* The caller's phone has already been customized to their preferences and able to dial numbers coded using best practices.

**Comment by 1Copenut** [comment]
Thank you @peggygannon . I changed that to "your" so the statement is general for whatever platform (web, Android, iOS) the reader is building on.

**Review by peggygannon — APPROVED** [review]
@1Copenut  just 1 more tweak, noted in my review. Otherwise looks good.

**Comment by 1Copenut** [comment]
@msmanak Would you mind taking a look at this PR for TTY if you have some time this week? Thank you!

**Review by peggygannon — APPROVED** [review]
update looks good.

**Review by msmanak — CHANGES_REQUESTED** [review]
did some copy changes and updated some process in the TTY call experience

**Comment by 1Copenut** [comment]
@peggygannon My apologies, I hit the wrong button and have inadvertently asked you for yet another review. Please feel free to ignore. Meli had some copy changes that she and I are coordinating on. Thank you!

**Pull request merged**
