### PR TITLE
508 Checklist from eBenefits

### PR DESCRIPTION
**Pull request by 1Copenut**
Moving the eBenefits 508 Checklist to the `/platform/accessibility` folder for all teams to make use of. I've created a new document that I'll merge into the platform folder, and we can coordinate removing the previous list and updating links.

### CODE REVIEW

**Review by jenstrickland — APPROVED** [review]
This is a great starting point.

**Comment by 1Copenut** [comment]
@jason-gcio I'll wait to get your PR approval before merging. This is your checklist with a few updates and a new home in `platform/accessibility`. Thanks much.

**Comment by sporeboy** [comment]
Looks good to me! :-)

**Review by sporeboy — APPROVED** [review]
Looks good--the additions are very helpful!

**Comment by jason-gcio** [comment]
Looks good, thanks for including us!

**Review by jason-gcio — COMMENTED** [review]
Looks good, thanks for including us!

**Pull request merged**
